### ISSUE TITLE
Sparse bit vector

### ISSUE THREAD

**Issue by faassen** [Cydhra/vers#16]
If you'll permit me to ask a question. 

If I understand it correctly, `RsVec` is not sparse; it's going to be on the order of the amount of bits to be stored plus some overhead to support rank and select. This makes it good as base for balanced parentheses.

To support tags in trees I also find myself in need of a sparse bit vector that supports rank and select. This is because each different tag has its own bitvec the same length as the BP bitvec, where a bit if set is the tag is in used for that node index. So typically only a few bits will be set compared to the bits unset. Do you know of a good Rust implementation of a sparse bitvec that supports these features?

**Comment by Cydhra** [comment]
I know that [RsDict](https://docs.rs/rsdict/latest/rsdict/) does compression, so this might qualify. sucds also has [SArray](https://docs.rs/sucds/0.8.1/sucds/bit_vectors/sarray/struct.SArray.html) for sparse bit vectors.

**Comment by faassen** [comment]
Thank you! I was also curious whether I could use a wavelet matrix for this purpose. I don't really understand the purpose of wavelet matrixes yet, but effectively for each parenthesis in the BP array, I associate a tag from an alphabet of tag ids. I then need the following operations to be fast:

* give me the tag id at index i
* rank and select for tag ids

It looks like it can store this information rather compactly, so perhaps it's in fact the right data structure for this purpose?

**Comment by Cydhra** [comment]
Wavelet matrices do give you rank/select for arbitrary alphabets in `O(s)` and can reconstruct any letter of the input text in `O(s)` as well, where `s` is the bit-length of your alphabet.
The required space is exactly the same as the input sequence (the wavelet matrix just rearranges the input bits), plus o(n) extra space as required by the bitvectors.

If you don't keep the input sequence, then the space overhead is manageable: essentially O(n) with a factor below 2. 

Whether rank/select on your tag alphabet is fast, you'd need to test in practice. The theoretical runtime is fast, but say you have a 16-bit alphabet, it requires 16 rank queries, which is a lot when compared to memory lookups, especially because you are almost guaranteed to have 16 cache misses for that. 

The sixteen cache misses can be cut in half when the underlying bit vector supports queries over `10` and `11` patterns, which is why I want that feature in the future.

**Comment by faassen** [comment]
The alphabet size in this case is on the order of how many different xml tags there are in an XML file, * 2 (separate symbols for open/ close versions of the tag). A couple of hundred tags is already quite a decent amount.

What do you mean by "you can reconstruct a letter"? Is that the get() indexing operation? As I was hoping it could do this in constant time.

I can experiment and compare it with an array of sparse bit arrays for rank/select supplemented by a main vector storing the tags for get().

**Comment by Cydhra** [comment]
> reconstruct a letter

The Wavelet matrix technically encodes the input sequence (for example a string, or a sequence of numeric values from a fixed range). It doesn't store the sequence explicitly but can reconstruct any letter of the sequence in O(s), so you don't need to store the sequence in addition to the wavelet matrix. It does not reconstruct letters in constant time, however.

**Comment by faassen** [comment]
As an update to this; I have now implemented the "associate tags with tree" functionality both with WaveletMatrix as well as with Sarray. But I haven't compared performance yet (though it strikes me that the sarray version may be faster), and constructing an actual tree from XML awaits my fm-index work where I'm currently overwhelmed. :)

**Comment by Cydhra** [comment]
Using a wavelet tree as a sparse bit-vector is probably possible using the approach you described, but I'd be very surprised if the performance was even close to a bit-vector implementation, let alone a sparse-bit-vector implementation.

If you need both libs and need to convert between the vectors, it might be a good idea to add a feature to vers that can convert them efficiently.
